"""Framework-independent scan domain models."""

from .content import (
    ContentDiagnostic,
    ContentScanResult,
    ContentScanStatus,
    LineMatch,
    MatchOptions,
    MatchSpan,
    scan_text,
)
from .credential_artifacts import (
    CredentialArtifactMatch,
    credential_artifact_header_bytes,
    detect_credential_artifact,
)
from .credentials import AuthMode, Credential, CredentialKind, CredentialValidationError
from .detection import (
    DEFAULT_DETECTION_RULES,
    DetectionConfidence,
    DetectionRule,
    PatternMatch,
    detect_patterns,
)
from .kerberos import resolve_kerberos_hostname
from .progress import (
    ActiveWork,
    ProgressSnapshot,
    ProgressTracker,
    ScanPhase,
    StaleProgressUpdate,
)
from .session import (
    CancellationSignal,
    CapacityReached,
    ResultCollection,
    ResultPage,
    ScanAlreadyRunning,
    ScanCancelled,
    ScanHandle,
    ScanSessionManager,
    ScanState,
    ScanStatus,
    ScanToken,
    SessionLimits,
    StaleScanUpdate,
    TerminalReason,
)
from .targets import (
    ExpandedTarget,
    ResolutionFailure,
    TargetKind,
    TargetParseError,
    TargetPlan,
    parse_targets,
)

__all__ = [
    "ActiveWork",
    "AuthMode",
    "Credential",
    "CredentialArtifactMatch",
    "CredentialKind",
    "CredentialValidationError",
    "DEFAULT_DETECTION_RULES",
    "DetectionConfidence",
    "DetectionRule",
    "CancellationSignal",
    "CapacityReached",
    "ContentDiagnostic",
    "ContentScanResult",
    "ContentScanStatus",
    "ExpandedTarget",
    "LineMatch",
    "MatchOptions",
    "MatchSpan",
    "PatternMatch",
    "ProgressSnapshot",
    "ProgressTracker",
    "ResultCollection",
    "ResultPage",
    "ResolutionFailure",
    "ScanPhase",
    "ScanAlreadyRunning",
    "ScanCancelled",
    "ScanHandle",
    "ScanSessionManager",
    "ScanState",
    "ScanStatus",
    "ScanToken",
    "SessionLimits",
    "StaleProgressUpdate",
    "StaleScanUpdate",
    "TargetKind",
    "TargetParseError",
    "TargetPlan",
    "TerminalReason",
    "parse_targets",
    "credential_artifact_header_bytes",
    "detect_credential_artifact",
    "detect_patterns",
    "resolve_kerberos_hostname",
    "scan_text",
]
